apiRules:
- include: # The namespaces to generate
    uidRegex: ^Doji\.AI\.Depth
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^Doji\.AI\.Depth\.Editor
- exclude:
    uidRegex: ^Doji\.AI\.Depth\.Samples