apiRules:
- include: # The namespaces to generate
    uidRegex: ^Midas
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: ^Midas\.Editor
- exclude:
    uidRegex: ^Midas\.Samples